
name: Build and Push Image to Dockerhub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_ORGANIZATION }}/camisim:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_ORGANIZATION }}/camisim:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_ORGANIZATION }}/camisim:buildcache,mode=max